# Generated by Django 5.2 on 2025-04-07 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentorados', '0005_terefas_upload'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Terefas',
            new_name='Tarefa',
        ),
    ]
