# Generated by Django 5.2.4 on 2025-08-02 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorados', '0006_rename_terefas_tarefa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='mentorado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentorados.mentorados'),
        ),
        migrations.AlterField(
            model_name='upload',
            name='mentorado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentorados.mentorados'),
        ),
    ]
